# Generated by Django 5.0.3 on 2024-03-22 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='banner',
            field=models.ImageField(upload_to='video-banner/', verbose_name='Изображение для видео'),
        ),
    ]
