# Generated by Django 5.0.3 on 2024-03-15 06:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Баннер', 'verbose_name_plural': 'Баннеры'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'видео', 'verbose_name_plural': 'видео'},
        ),
        migrations.AddField(
            model_name='video',
            name='name',
            field=models.CharField(default='lalalala', max_length=255, verbose_name='Название видео'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='banner/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='subtitle',
            field=models.CharField(max_length=255, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='video',
            name='banner',
            field=models.ImageField(upload_to='video_banner/', verbose_name='Изображение баннера'),
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.URLField(verbose_name='URL-адрес YouTube я'),
        ),
    ]
