# Generated by Django 5.0.3 on 2024-04-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='button_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на кнопку'),
        ),
        migrations.AddField(
            model_name='banner',
            name='has_button',
            field=models.BooleanField(default=False, verbose_name='Есть кнопка?'),
        ),
    ]
