# Generated by Django 5.0.3 on 2024-03-28 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_callback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Callback',
        ),
    ]
