# Generated by Django 5.0.3 on 2024-03-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_alter_banner_id_alter_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='video-banners/'),
        ),
    ]
