# Generated by Django 5.0.3 on 2024-04-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_alter_expert_options_video_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='type',
            field=models.CharField(choices=[('main', 'основные'), ('event', 'мероприятие')], max_length=10),
        ),
    ]
