# Generated by Django 5.0.3 on 2024-03-19 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_video_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='video',
            name='banner',
            field=models.ImageField(upload_to='video-banners/'),
        ),
    ]
