# Generated by Django 5.0.3 on 2024-03-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_rename_name_video_title_alter_video_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='banner',
            field=models.ImageField(upload_to='video-banners/', verbose_name='Изображение для видео'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
