# Generated by Django 5.0.3 on 2024-03-15 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_rename_banner_video_banner_image_alter_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='banner_image',
        ),
    ]
