# Generated by Django 5.0.3 on 2024-03-20 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0006_alter_news_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['-id'], 'verbose_name': 'Баннер', 'verbose_name_plural': 'Баннеры'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-id'], 'verbose_name': 'видео', 'verbose_name_plural': 'видео'},
        ),
    ]
