# Generated by Django 5.0.3 on 2024-03-20 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('image', models.ImageField(null=True, upload_to='category/', verbose_name='Изображение')),
                ('is_top', models.BooleanField(default=False, verbose_name='Верхнее меню?')),
                ('is_left', models.BooleanField(default=False, verbose_name='Левое меню?')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='product.basecategory', verbose_name='Высшая категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['-is_top'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('product.basecategory',),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
                'ordering': ['-parent__is_top', '-parent', 'name'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('product.basecategory',),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название продукта')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('is_new', models.BooleanField(default=False, verbose_name='Новый?')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('vendor_code', models.CharField(max_length=32, verbose_name='Артикул')),
                ('history', models.CharField(max_length=255, verbose_name='История')),
                ('characteristic', models.CharField(max_length=255, verbose_name='Характеристики')),
                ('size', models.CharField(max_length=255, verbose_name='Размер')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на видео о продукте на YouTube')),
                ('category', models.ManyToManyField(related_name='products', to='product.basecategory', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['-created', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='products/')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product')),
            ],
            options={
                'verbose_name': 'product image',
                'verbose_name_plural': 'product images',
            },
        ),
    ]
