# Generated by Django 5.0.3 on 2024-03-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_subcategory_options_alter_basecategory_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoldProduct',
            fields=[
            ],
            options={
                'verbose_name': 'Проданный продукт',
                'verbose_name_plural': 'Проданная продукция',
                'ordering': ['-is_new', 'name'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('product.product',),
        ),
        migrations.AddField(
            model_name='product',
            name='is_sold',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Продано?'),
        ),
    ]
