# Generated by Django 5.0.3 on 2024-03-16 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_discount_product_authorship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='art',
        ),
        migrations.AddField(
            model_name='product',
            name='vendor_code',
            field=models.CharField(default='D000022A', max_length=32, verbose_name='Артикул'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='basecategory',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='characteristic',
            field=models.CharField(max_length=255, verbose_name='Характеристики'),
        ),
        migrations.AlterField(
            model_name='product',
            name='history',
            field=models.CharField(max_length=255, verbose_name='История'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название продукта'),
        ),
    ]
