# Generated by Django 5.0.3 on 2024-05-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='products',
            field=models.ManyToManyField(related_name='filter', to='product.product', verbose_name='Продукты'),
        ),
    ]
