# Generated by Django 5.0.3 on 2024-03-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_basecategory_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-is_new', 'name'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterField(
            model_name='basecategory',
            name='is_left',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Левое меню?'),
        ),
        migrations.AlterField(
            model_name='basecategory',
            name='is_top',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Верхнее меню?'),
        ),
        migrations.AlterField(
            model_name='basecategory',
            name='name',
            field=models.CharField(db_index=True, max_length=128, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='characteristic',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Характеристики'),
        ),
        migrations.AlterField(
            model_name='product',
            name='history',
            field=models.CharField(db_index=True, max_length=255, verbose_name='История'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Новый?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Название продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor_code',
            field=models.CharField(db_index=True, max_length=32, verbose_name='Артикул'),
        ),
    ]
