# Generated by Django 5.0.3 on 2024-05-30 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_filter_name_alter_filter_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecategory',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
