# Generated by Django 5.0.3 on 2024-05-31 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_basecategory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecategory',
            name='title',
            field=models.CharField(default='', max_length=256, verbose_name='Заголовок'),
            preserve_default=False,
        ),
    ]
