# Generated by Django 5.0.3 on 2024-03-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_product_is_available_remove_product_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на видео о продукте на YouTube'),
        ),
    ]
