# Generated by Django 5.0.3 on 2024-05-31 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_basecategory_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='L3Category',
            fields=[
            ],
            options={
                'verbose_name': 'Подподкатегория',
                'verbose_name_plural': 'Подподкатегории',
                'ordering': ['-parent__is_top', 'parent__name', 'name'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('product.basecategory',),
        ),
    ]
