# Generated by Django 5.0.3 on 2024-06-12 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_l3category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='commentary',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
    ]
