# Generated by Django 5.0.3 on 2024-03-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_product_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecategory',
            name='left_menu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='basecategory',
            name='top_menu',
            field=models.BooleanField(default=False),
        ),
    ]
