# Generated by Django 5.0.3 on 2024-06-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_commentary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecategory',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='basecategory',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Заголовок'),
        ),
    ]
