# Generated by Django 5.0.3 on 2024-03-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_basecategory_left_menu_basecategory_top_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecategory',
            name='left_menu',
            field=models.BooleanField(default=False, verbose_name='Левое меню'),
        ),
        migrations.AlterField(
            model_name='basecategory',
            name='top_menu',
            field=models.BooleanField(default=False, verbose_name='Верхнее меню'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='products', to='product.basecategory', verbose_name='Категории'),
        ),
    ]
