# Generated by Django 5.0.3 on 2024-03-20 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_basecategory_id_alter_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basecategory',
            name='left_menu',
        ),
        migrations.RemoveField(
            model_name='basecategory',
            name='top_menu',
        ),
        migrations.AddField(
            model_name='basecategory',
            name='is_left',
            field=models.BooleanField(default=False, verbose_name='Левое меню?'),
        ),
        migrations.AddField(
            model_name='basecategory',
            name='is_top',
            field=models.BooleanField(default=False, verbose_name='Верхнее меню?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='product.basecategory', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='product',
            name='characteristic',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Характеристики'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='history',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='История'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Новый?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.TextField(blank=True, null=True, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor_code',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Артикул'),
        ),
    ]
