# Generated by Django 5.0.3 on 2024-03-20 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='products', to='product.basecategory', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='product',
            name='characteristic',
            field=models.CharField(default='Серебро 875 проба, чеканка, гравировка; стекло ручного выдувания.', max_length=255, verbose_name='Характеристики'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='history',
            field=models.CharField(max_length=255, verbose_name='История'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='Новый?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.TextField(verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor_code',
            field=models.CharField(max_length=32, verbose_name='Артикул'),
        ),
    ]
