# Generated by Django 5.0.3 on 2024-03-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_product_category_alter_product_characteristic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(max_length=255, verbose_name='Размер'),
        ),
    ]
