# Generated by Django 5.0.3 on 2024-03-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(default='/media/images/2bbf2a42-bed3-4136-b624-1688b6019860/000000_474750903_kdpmpp2m15_PS7.5__._digital_KHl6GDn.jpg', upload_to='news/'),
            preserve_default=False,
        ),
    ]
