# Generated by Django 5.0.3 on 2024-03-11 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='amount',
            field=models.IntegerField(default=1234),
            preserve_default=False,
        ),
    ]
